#
# Base services for beluga.
#
#   This is the initial part of the docker-compose.yml file to
#   be used in a beluga setup. Additional services are appended
#   to this file to make a particular docker-compose.yml
#
version: '2'

networks:
  default:
    external:
      name: beluga

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  dnsmasq:
    build: ./dnsmasq
    image: caspia/dnsmasq:alpine
    container_name: dnsmasq
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    env_file: .env
    command: ["-A", "/${DOMAIN}/${IP_ADDR}"]
    environment:
      - IP_ADDR=$IP_ADDR
    cap_add:
      - NET_ADMIN
